spring.application.name=diplom
server.port=8081

# Map file to load on startup (map.osm for fast startup and low RAM, Moscow.osm for full city)
#app.map-file-name=map.osm
app.map-file-name=Moscow.osm

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=Artem
spring.datasource.password=Real2310
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=routing-service-group-v2
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.kafka.traffic-topic=traffic-events
